### ISSUE TITLE
Production deployment with real certificates?

### ISSUE THREAD

**Issue by davidaik** [blink38/signserver#2]
Hi. Did you ever deploy SignServer with real certificates. Could you please point me in the right direction to do the same if you did?

**Comment by blink38** [comment]
No, I do not deploy SignServer with real certificates. But I might not be very different.

**Comment by davidaik** [comment]
Thanks for the response. I've been looking into deploying it to production for my employer but I'm a bit confused about some things. In any case, I'll keep looking :)

**Comment by blink38** [comment]
I deployed an old version. I see that a new version have been released since my deployment.
